import 'module-alias/register';
import { MTahapan } from "@/app/models/MTahapan";

export class MTahapanSeeder {
    static async run() {
        await MTahapan.insert([
    {
        "id": 1,
        "tahun_buku": 2022,
        "posisi": 1,
        "nama": "R-APBD 1 (Buku Putih)",
        "jenis": "murni",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 1,
        "tahun_buku": 2023,
        "posisi": 1,
        "nama": "RKPD",
        "jenis": "murni",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 1,
        "tahun_buku": 2024,
        "posisi": 1,
        "nama": "R-KUA-PPAS",
        "jenis": "murni",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 2,
        "tahun_buku": 2022,
        "posisi": 2,
        "nama": "R-APBD 2 (Buku Biru)",
        "jenis": "murni",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 2,
        "tahun_buku": 2023,
        "posisi": 2,
        "nama": "PPAS Murni Final",
        "jenis": "murni",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 2,
        "tahun_buku": 2024,
        "posisi": 2,
        "nama": "PPAS Murni Final",
        "jenis": "murni",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 3,
        "tahun_buku": 2022,
        "posisi": 3,
        "nama": "APBD (Murni)",
        "jenis": "murni",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 3,
        "tahun_buku": 2024,
        "posisi": 3,
        "nama": "R-APBD 1 (Buku Putih)",
        "jenis": "murni",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 4,
        "tahun_buku": 2022,
        "posisi": 4,
        "nama": "Revisi 1",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 4,
        "tahun_buku": 2024,
        "posisi": 4,
        "nama": "R-APBD 2 (Buku Biru)",
        "jenis": "murni",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 5,
        "tahun_buku": 2022,
        "posisi": 5,
        "nama": "Revisi 2",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 5,
        "tahun_buku": 2023,
        "posisi": 3,
        "nama": "R-APBD 1 (Buku Putih)",
        "jenis": "murni",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 5,
        "tahun_buku": 2024,
        "posisi": 5,
        "nama": "APBD (Murni)",
        "jenis": "murni",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 6,
        "tahun_buku": 2023,
        "posisi": 4,
        "nama": "R-APBD 2 (Buku Biru)",
        "jenis": "murni",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 6,
        "tahun_buku": 2024,
        "posisi": 6,
        "nama": "Revisi 1",
        "jenis": "revisi",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 7,
        "tahun_buku": 2022,
        "posisi": 6,
        "nama": "MPAK",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 7,
        "tahun_buku": 2023,
        "posisi": 5,
        "nama": "APBD (Murni)",
        "jenis": "murni",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 7,
        "tahun_buku": 2024,
        "posisi": 7,
        "nama": "MPAK",
        "jenis": "revisi",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 1,
        "is_used_belanja": 0
    },
    {
        "id": 8,
        "tahun_buku": 2022,
        "posisi": 7,
        "nama": "M-PAK",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 8,
        "tahun_buku": 2023,
        "posisi": 6,
        "nama": "Revisi 1",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 8,
        "tahun_buku": 2024,
        "posisi": 8,
        "nama": "Revisi 2",
        "jenis": "revisi",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 9,
        "tahun_buku": 2022,
        "posisi": 8,
        "nama": "Revisi 3",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 9,
        "tahun_buku": 2023,
        "posisi": 7,
        "nama": "Revisi 1 - SPD",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 9,
        "tahun_buku": 2024,
        "posisi": 9,
        "nama": "Revisi 3",
        "jenis": "revisi",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 10,
        "tahun_buku": 2022,
        "posisi": 9,
        "nama": "KUA-PPAS PAK",
        "jenis": "pak",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 10,
        "tahun_buku": 2023,
        "posisi": 8,
        "nama": "Revisi 2",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 10,
        "tahun_buku": 2024,
        "posisi": 10,
        "nama": "Revisi 4",
        "jenis": "revisi",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 11,
        "tahun_buku": 2022,
        "posisi": 10,
        "nama": "Revisi 4",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 11,
        "tahun_buku": 2023,
        "posisi": 9,
        "nama": "Revisi 2 - SPD",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 11,
        "tahun_buku": 2024,
        "posisi": 11,
        "nama": "MPAK 2",
        "jenis": "revisi",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 1
    },
    {
        "id": 12,
        "tahun_buku": 2022,
        "posisi": 11,
        "nama": "MPAK 2",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 12,
        "tahun_buku": 2023,
        "posisi": 10,
        "nama": "Revisi 2 - SPD (1)",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 12,
        "tahun_buku": 2024,
        "posisi": 12,
        "nama": "RKUA PAK",
        "jenis": "pak",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 13,
        "tahun_buku": 2022,
        "posisi": 13,
        "nama": "MPAK 3",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 13,
        "tahun_buku": 2023,
        "posisi": 11,
        "nama": "MPAK",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 13,
        "tahun_buku": 2024,
        "posisi": 13,
        "nama": "R-PAK 1 (Buku Putih)",
        "jenis": "pak",
        "insert_date": "2024-07-30T01:23:29.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 14,
        "tahun_buku": 2022,
        "posisi": 12,
        "nama": "Revisi 5",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 14,
        "tahun_buku": 2023,
        "posisi": 12,
        "nama": "Revisi 3",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 15,
        "tahun_buku": 2022,
        "posisi": 14,
        "nama": "PPAS PAK Final",
        "jenis": "pak",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 15,
        "tahun_buku": 2023,
        "posisi": 13,
        "nama": "Revisi 4",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 16,
        "tahun_buku": 2022,
        "posisi": 15,
        "nama": "R-PAK 1 (Buku Putih)",
        "jenis": "pak",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 16,
        "tahun_buku": 2023,
        "posisi": 14,
        "nama": "Revisi 5",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 17,
        "tahun_buku": 2022,
        "posisi": 16,
        "nama": "R-PAK 2 (Buku Biru)",
        "jenis": "pak",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 17,
        "tahun_buku": 2023,
        "posisi": 15,
        "nama": "R-KUA-PPAS PAK",
        "jenis": "pak",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 18,
        "tahun_buku": 2022,
        "posisi": 17,
        "nama": "PAK Penetapan",
        "jenis": "pak",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 18,
        "tahun_buku": 2023,
        "posisi": 16,
        "nama": "Revisi 6",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 19,
        "tahun_buku": 2022,
        "posisi": 18,
        "nama": "Revisi 6",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 19,
        "tahun_buku": 2023,
        "posisi": 17,
        "nama": "R-PAK 1 (Buku Putih)",
        "jenis": "pak",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 20,
        "tahun_buku": 2022,
        "posisi": 19,
        "nama": "Revisi 7",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 20,
        "tahun_buku": 2023,
        "posisi": 18,
        "nama": "R-PAK 2 (Buku Biru)",
        "jenis": "pak",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 21,
        "tahun_buku": 2022,
        "posisi": 20,
        "nama": "Revisi 8",
        "jenis": "revisi",
        "insert_date": "2024-05-30T07:41:25.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 21,
        "tahun_buku": 2023,
        "posisi": 19,
        "nama": "PAK Penetapan",
        "jenis": "pak",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 22,
        "tahun_buku": 2023,
        "posisi": 20,
        "nama": "Revisi 7",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 0,
        "is_used_belanja": 0
    },
    {
        "id": 23,
        "tahun_buku": 2023,
        "posisi": 21,
        "nama": "Revisi 8",
        "jenis": "revisi",
        "insert_date": "2024-04-16T07:44:27.000Z",
        "insert_by": "MASTER",
        "is_used": 1,
        "is_used_belanja": 0
    }
]);
    }
}
